dist: trusty
sudo: false

language: node_js
node_js:
  - "node"

cache:
  directories:
    - ./node_modules

install:
  - yarn install --frozen-lockfile

script:
  - yarn build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
